# Install pre-commit hooks with 'task setup:pre-commit'
# Run pre-commit hooks with 'task pre-commit'

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        exclude: '^.gitlab-ci.yml'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.10
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--preview, --fix]
      # Run the formatter.
      - id: ruff-format
        args: [--preview]

  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt

  - repo: https://github.com/PyCQA/bandit
    rev: '1.8.3'
    hooks:
      - id: bandit
        args:
          - -c
          - pyproject.toml
          - --confidence-level
          - medium
          - --severity-level
          - medium
        additional_dependencies:
          - "bandit[toml]"

  - repo: local
    hooks:
      - id: readme:generate-toc
        name: Generate README Table of Contents
        language: system
        entry: uvx --from md-toc md_toc --in-place cmark README.md
        files: |-
          ^README\.md$
